[package]
name = "test_suite_cli"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
rand.workspace = true
itertools.workspace = true
hcaptcha = { path = "../hcaptcha" }
serde_json.workspace = true
