[package]
name = "hcaptcha"
description = """
hCaptcha client response verification. Validate the hCaptcha response submitted from to your server from the client.
"""
version = "2.1.0"
authors = ["Jeremiah Russell <jrussell@jerus.ie>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jerusdp/hcaptcha-rs"
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/hcaptcha"
categories = ["web-programming"]
keywords = ["hcaptcha", "captcha", "security", "backend", "protection"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "CHANGES.md",
]

[features]
default = ["ext"]
ext = ["hex"]
enterprise = []
trace = ["tracing"]
nightly = []

[dependencies]
async-trait = "0.1"
hex = { version = "0.4", optional = true }
reqwest = { version = "0.11.6", features = ["json"] }
serde_json = "1.0.71"
serde_urlencoded = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0"
tracing = { version = "0.1.29", features = ["log", "attributes"], optional = true }
uuid = "0.8.2"
url = "2.2.2"
hcaptcha_derive = { version = "2.0.0", path = "../hcaptcha_derive" }

[dev-dependencies]
chrono = "0.4.19"
claim = "0.5.0"
fakeit = "1.1.1"
hex = "0.4"
itertools = "0.10.1"
lambda_runtime = "0.4.1"
log = "0.4.14"
rand= "0.8.4"
simple_logger = "1.16.0"
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-bunyan-formatter = "0.3.0"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
tracing-test = "0.1.0"
rusoto_core = {version = "0.47.0", default_features = false, features=["rustls"]}
rusoto_ses = {version = "0.47.0", default_features = false, features=["rustls"]}
wiremock = "0.5"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
