language: rust
  script:
    - cargo build --verbose 
    - cargo test --verbose --lib
branches:
  only:
    - main
rust:
  - 1.45.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true