version: 2.1

parameters:
  min-rust-version:
    type: string
    default: "1.75"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg

executors:
  rust-env:
    docker:
      - image: jerusdp/ci-rust:<<pipeline.parameters.min-rust-version>>

jobs:
  show_success:
    executor: rust-env
    steps:
      - run: |
          echo "Completed successfully!"

workflows:
  success:
    jobs:
      - show_success
