name: release-please

on:
   push:
     branches:
       - main

permissions:
  contents: read

jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: rust
